/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetoa3;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author spect
 */
public class FilaAtendimento extends javax.swing.JFrame {

   
    public void consultaUrgencia() throws Exception{
        DefaultTableModel model = (DefaultTableModel)tableUrgencia.getModel();
        model.setRowCount(1);

      String sql = "select paciente.nome , status_aten, tipo from atendimento inner join paciente on atendimento.Paciente_cpf = paciente.cpf where tipo = 1";

        try(Connection conn = ConexaoDB.obtemConexao();
           PreparedStatement ps = conn.prepareStatement(sql)){
            ResultSet rs = ps.executeQuery();

            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3)});
            }
        
        }}
    
     public void consultaEmergencia() throws Exception{
        DefaultTableModel model = (DefaultTableModel)tableEmergencia.getModel();
        model.setRowCount(1);

      String sql = "select paciente.nome , status_aten, tipo from atendimento inner join paciente on atendimento.Paciente_cpf = paciente.cpf where tipo = 2";

        try(Connection conn = ConexaoDB.obtemConexao();
           PreparedStatement ps = conn.prepareStatement(sql)){
            ResultSet rs = ps.executeQuery();

            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3)});
            }
        
        }}
     
      public void consultaPreferencial() throws Exception{
        DefaultTableModel model = (DefaultTableModel)tablePreferencial.getModel();
        model.setRowCount(1);

      String sql = "select paciente.nome , status_aten, tipo from atendimento inner join paciente on atendimento.Paciente_cpf = paciente.cpf where tipo = 3";

        try(Connection conn = ConexaoDB.obtemConexao();
           PreparedStatement ps = conn.prepareStatement(sql)){
            ResultSet rs = ps.executeQuery();

            while(rs.next()){
                model.addRow(new String[]{rs.getString(1), rs.getString(2), rs.getString(3)});
            }
        
        }}

    
    
    
    public FilaAtendimento() {
        super("Fila de Atendimento");
        initComponents();
        this.setLocationRelativeTo(null);

    try{
    
    
    consultaPreferencial();
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, "Não foi possível buscar os dados do Banco."); 
    }  
        
        
    try{
    
    
    consultaUrgencia();
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, "Não foi possível buscar os dados do Banco."); 
    }   
    
     try{
    
    
    consultaEmergencia();
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, "Não foi possível buscar os dados do Banco."); 
    }
    }

    
        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TX1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableEmergencia = new javax.swing.JTable();
        SetinhaIMG = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablePreferencial = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableUrgencia = new javax.swing.JTable();
        TX2 = new javax.swing.JLabel();
        TX3 = new javax.swing.JLabel();
        TX4 = new javax.swing.JLabel();
        MenuBarra = new javax.swing.JMenuBar();
        Login = new javax.swing.JMenu();
        Atendente = new javax.swing.JMenuItem();
        Cadastro = new javax.swing.JMenu();
        Paciente = new javax.swing.JMenuItem();
        Atendimento = new javax.swing.JMenu();
        Registro = new javax.swing.JMenuItem();
        Fila = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 113, 182));

        TX1.setBackground(new java.awt.Color(255, 255, 255));
        TX1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        TX1.setForeground(new java.awt.Color(255, 255, 255));
        TX1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TX1.setText("Fila de Atendimento");

        tableEmergencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Status", "Tipo"
            }
        ));
        jScrollPane3.setViewportView(tableEmergencia);

        SetinhaIMG.setIcon(new javax.swing.ImageIcon("C:\\Users\\spect\\OneDrive\\Documentos\\NetBeansProjects\\ProjetoA3\\imagem\\Setinha.png")); // NOI18N

        tablePreferencial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Status", "Tipo"
            }
        ));
        jScrollPane4.setViewportView(tablePreferencial);

        tableUrgencia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Status", "Tipo"
            }
        ));
        jScrollPane5.setViewportView(tableUrgencia);

        TX2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        TX2.setForeground(new java.awt.Color(255, 255, 255));
        TX2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TX2.setText("Urgência");
        TX2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 37, 59)));

        TX3.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        TX3.setForeground(new java.awt.Color(255, 255, 255));
        TX3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TX3.setText("Emergência");
        TX3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 37, 59)));

        TX4.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        TX4.setForeground(new java.awt.Color(255, 255, 255));
        TX4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TX4.setText("Preferencial");
        TX4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 37, 59)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(SetinhaIMG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TX1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TX4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TX2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TX3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TX1)
                    .addComponent(SetinhaIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(TX2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TX3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(TX4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        Login.setText("Login");

        Atendente.setText("Atendente");
        Atendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtendenteActionPerformed(evt);
            }
        });
        Login.add(Atendente);

        MenuBarra.add(Login);

        Cadastro.setText("Cadastro");

        Paciente.setText("Paciente");
        Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacienteActionPerformed(evt);
            }
        });
        Cadastro.add(Paciente);

        MenuBarra.add(Cadastro);

        Atendimento.setText("Atendimento");

        Registro.setText("Registrar Consulta");
        Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroActionPerformed(evt);
            }
        });
        Atendimento.add(Registro);

        Fila.setText("Fila");
        Fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilaActionPerformed(evt);
            }
        });
        Atendimento.add(Fila);

        MenuBarra.add(Atendimento);

        setJMenuBar(MenuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtendenteActionPerformed
      TelaLogin tl = new TelaLogin();
      tl.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_AtendenteActionPerformed

    private void PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacienteActionPerformed
        Cadastro ca = new Cadastro();
        ca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PacienteActionPerformed

    private void FilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FilaActionPerformed

    private void RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroActionPerformed
        RegistrarConsulta rc = new RegistrarConsulta();
        rc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilaAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilaAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilaAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilaAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilaAtendimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Atendente;
    private javax.swing.JMenu Atendimento;
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenuItem Fila;
    private javax.swing.JMenu Login;
    private javax.swing.JMenuBar MenuBarra;
    private javax.swing.JMenuItem Paciente;
    private javax.swing.JMenuItem Registro;
    private javax.swing.JLabel SetinhaIMG;
    private javax.swing.JLabel TX1;
    private javax.swing.JLabel TX2;
    private javax.swing.JLabel TX3;
    private javax.swing.JLabel TX4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable tableEmergencia;
    private javax.swing.JTable tablePreferencial;
    private javax.swing.JTable tableUrgencia;
    // End of variables declaration//GEN-END:variables
}
