/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetoa3;

import javax.swing.JOptionPane;

/**
 *
 * @author spect
 */
public class RegistrarConsulta extends javax.swing.JFrame {

    /**
     * Creates new form NFrame
     */
    public RegistrarConsulta() {
        super("Registro de Consulta");
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TX1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        TX2 = new javax.swing.JLabel();
        TX01 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        TX02 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        TX6 = new javax.swing.JLabel();
        txtData = new javax.swing.JTextField();
        botaoAtualizar = new javax.swing.JButton();
        botaoFila = new javax.swing.JButton();
        TX7 = new javax.swing.JLabel();
        txtTipo = new javax.swing.JTextField();
        TX8 = new javax.swing.JLabel();
        txtEsp = new javax.swing.JTextField();
        txtPressao = new javax.swing.JTextField();
        TX9 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        TX10 = new javax.swing.JLabel();
        TX11 = new javax.swing.JLabel();
        txtTemp = new javax.swing.JTextField();
        TX12 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        TX13 = new javax.swing.JLabel();
        txtSintomas = new javax.swing.JTextField();
        TX14 = new javax.swing.JLabel();
        txtFreq = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jList5 = new javax.swing.JList<>();
        jSeparator2 = new javax.swing.JSeparator();
        SetinhaIMG = new javax.swing.JLabel();
        MenuBarra = new javax.swing.JMenuBar();
        Login = new javax.swing.JMenu();
        Atendente = new javax.swing.JMenuItem();
        Cadastro = new javax.swing.JMenu();
        Paciente = new javax.swing.JMenuItem();
        Atendimento = new javax.swing.JMenu();
        Registro = new javax.swing.JMenuItem();
        Fila = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 113, 182));

        TX1.setBackground(new java.awt.Color(255, 255, 255));
        TX1.setFont(new java.awt.Font("Bahnschrift", 1, 24)); // NOI18N
        TX1.setForeground(new java.awt.Color(255, 255, 255));
        TX1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TX1.setText("Atendimento");

        jSeparator1.setBackground(new java.awt.Color(249, 37, 59));
        jSeparator1.setForeground(new java.awt.Color(249, 37, 59));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TX2.setFont(new java.awt.Font("Bahnschrift", 0, 18)); // NOI18N
        TX2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TX2.setText("Atualização de Dados");
        TX2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(249, 37, 59)));

        TX01.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        TX01.setText("ID:");

        TX02.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        TX02.setText("CPF: ");

        TX6.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        TX6.setText("Data:");

        botaoAtualizar.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        botaoAtualizar.setForeground(new java.awt.Color(0, 113, 182));
        botaoAtualizar.setText("Atualizar");
        botaoAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarActionPerformed(evt);
            }
        });

        botaoFila.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        botaoFila.setForeground(new java.awt.Color(0, 113, 182));
        botaoFila.setText("Exibir Fila");
        botaoFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFilaActionPerformed(evt);
            }
        });

        TX7.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        TX7.setText("Tipo:");

        TX8.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        TX8.setText("Especialidade:");

        TX9.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        TX9.setText("N°:");

        TX10.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        TX10.setText("Pressão Arterial: ");

        TX11.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        TX11.setText("Temperatura:");

        TX12.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        TX12.setText("Frequência Cardíaca: ");

        TX13.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        TX13.setText("Sintomas: ");

        TX14.setFont(new java.awt.Font("Bahnschrift", 0, 14)); // NOI18N
        TX14.setText("Status:");

        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1- Aguardando", "2- Encaminhado", "3- Concluído" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jList3);

        jList4.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1- Cardiologista", "2- Ortopedista", "3- Pediatria" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList4);

        jList5.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1- Urgência", "2- Emergência", "3- Preferencial" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jList5);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TX11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(TX13))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TX01)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(TX02)
                                .addGap(18, 18, 18)
                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(TX6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(TX9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TX14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoAtualizar)
                        .addGap(74, 74, 74)
                        .addComponent(botaoFila)
                        .addGap(248, 248, 248))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TX7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TX8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane5))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(TX12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtFreq, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(TX10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                                .addComponent(txtPressao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(65, 65, 65))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TX2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TX2)
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TX01)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TX02)
                    .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TX6)
                    .addComponent(TX9)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TX7)
                        .addComponent(TX8)
                        .addComponent(txtEsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TX11)
                    .addComponent(txtTemp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TX13)
                    .addComponent(txtSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TX12)
                    .addComponent(txtFreq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPressao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TX10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TX14)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoFila, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jSeparator2.setBackground(new java.awt.Color(249, 37, 59));
        jSeparator2.setForeground(new java.awt.Color(249, 37, 59));

        SetinhaIMG.setIcon(new javax.swing.ImageIcon("C:\\Users\\spect\\OneDrive\\Documentos\\NetBeansProjects\\ProjetoA3\\imagem\\Setinha.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 262, Short.MAX_VALUE)
                .addComponent(SetinhaIMG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TX1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(jSeparator2))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(17, 17, 17))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SetinhaIMG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TX1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        Login.setText("Login");

        Atendente.setText("Atendente");
        Atendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtendenteActionPerformed(evt);
            }
        });
        Login.add(Atendente);

        MenuBarra.add(Login);

        Cadastro.setText("Cadastro");

        Paciente.setText("Paciente");
        Paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PacienteActionPerformed(evt);
            }
        });
        Cadastro.add(Paciente);

        MenuBarra.add(Cadastro);

        Atendimento.setText("Atendimento");

        Registro.setText("Registrar Consulta");
        Atendimento.add(Registro);

        Fila.setText("Fila");
        Fila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FilaActionPerformed(evt);
            }
        });
        Atendimento.add(Fila);

        MenuBarra.add(Atendimento);

        setJMenuBar(MenuBarra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtendenteActionPerformed
        TelaLogin tl = new TelaLogin();
        tl.setVisible(true);
        this.dispose();      
    }//GEN-LAST:event_AtendenteActionPerformed

    private void PacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PacienteActionPerformed
        Cadastro ca = new Cadastro();
        ca.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PacienteActionPerformed

    private void FilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FilaActionPerformed
        FilaAtendimento fa = new FilaAtendimento();
        fa.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_FilaActionPerformed

    private void botaoFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFilaActionPerformed
        FilaAtendimento fa = new FilaAtendimento();
        fa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botaoFilaActionPerformed

    private void botaoAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAtualizarActionPerformed
        int id = Integer.parseInt(txtID.getText());
        int esp = Integer.parseInt(txtEsp.getText());
        String cpf = txtCPF.getText();
        String data = txtData.getText();
        int tipo = Integer.parseInt(txtTipo.getText());
        int num = Integer.parseInt(txtNumero.getText());
        float pressao = Float.parseFloat(txtPressao.getText());
        float temp = Float.parseFloat(txtTemp.getText());
        String sintomas = txtSintomas.getText();
        float freq = Float.parseFloat(txtFreq.getText());
        int status = Integer.parseInt(txtStatus.getText());
        
        
        try{
           Atendimento atend = new Atendimento(id, esp, cpf, data, tipo, num, pressao, temp, sintomas, freq, status);
           DAO dao = new DAO();
           dao.atualizarConsulta(atend);
           JOptionPane.showMessageDialog(null, "Dados da consulta atualizados com sucesso!");
           
            txtID.setText("");
            txtEsp.setText("");
            txtCPF.setText("");
            txtData.setText("");
            txtTipo.setText("");
            txtNumero.setText("");
            txtPressao.setText("");
            txtTemp.setText("");
            txtSintomas.setText("");
            txtFreq.setText("");
            txtStatus.setText("");
                    
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Não foi possivel atualizar os dados da consulta!");
        }
    }//GEN-LAST:event_botaoAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Atendente;
    private javax.swing.JMenu Atendimento;
    private javax.swing.JMenu Cadastro;
    private javax.swing.JMenuItem Fila;
    private javax.swing.JMenu Login;
    private javax.swing.JMenuBar MenuBarra;
    private javax.swing.JMenuItem Paciente;
    private javax.swing.JMenuItem Registro;
    private javax.swing.JLabel SetinhaIMG;
    private javax.swing.JLabel TX01;
    private javax.swing.JLabel TX02;
    private javax.swing.JLabel TX1;
    private javax.swing.JLabel TX10;
    private javax.swing.JLabel TX11;
    private javax.swing.JLabel TX12;
    private javax.swing.JLabel TX13;
    private javax.swing.JLabel TX14;
    private javax.swing.JLabel TX2;
    private javax.swing.JLabel TX6;
    private javax.swing.JLabel TX7;
    private javax.swing.JLabel TX8;
    private javax.swing.JLabel TX9;
    private javax.swing.JButton botaoAtualizar;
    private javax.swing.JButton botaoFila;
    private javax.swing.JList<String> jList3;
    private javax.swing.JList<String> jList4;
    private javax.swing.JList<String> jList5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtData;
    private javax.swing.JTextField txtEsp;
    private javax.swing.JTextField txtFreq;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPressao;
    private javax.swing.JTextField txtSintomas;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTemp;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
